# Generated by Django 4.2.16 on 2024-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='img_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
