# Generated by Django 4.2.16 on 2024-11-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
