# Generated by Django 4.2.16 on 2024-11-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_searchterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_data_scraped', models.IntegerField()),
                ('pages_scraped', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
